version: 0.2
env:
  shell: bash
  exported-variables:
    - STAGE
    - GIT_BRANCH
        
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - 'GIT_BRANCH=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed "s|.*/||")'
      - 'git checkout $GIT_BRANCH'
      - 'wget -O /usr/local/bin/tfenv https://github.com/cloudposse/tfenv/releases/download/0.4.0/tfenv_linux_amd64'
      - 'chmod +x /usr/local/bin/tfenv'
      - 'curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -'
      - 'curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -'
      - 'echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list'
      - 'apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"'
      - 'chmod a+rx utils -R'
      - 'apt-get update -y'
      - 'apt-get install zip terraform yarn -y'
      - 'yarn global add json dotenv-cli --prefix /usr/local'
      - 'export STAGE=$(utils/branch-to-stage.sh config.json)'
      - 'echo "Code building for branch: $GIT_BRANCH  :  corresponds to stage  :  $STAGE"'
      - 'aws s3 cp s3://meandering-rocks-configuration/env/.env.$STAGE .env.$STAGE'
      - 'yarn install'
  pre_build:
    commands:
      - 'yarn run test:since-$(git branch --show-current)'

  build:
    commands:
      - 'yarn run build:tf-required'
      - 'cd web'
      - 'yarn run build'
      - 'cd ..'
      - 'echo "Terraform planning environment resources for stage: common"'
      - 'terraform -chdir=tf/common init'
      - 'dotenv -e .env.$STAGE -- tfenv terraform -chdir=tf/common plan -out=.tfplan-common'
      - 'echo "Terraform planning environment resources for stage: $STAGE"'
      - 'terraform -chdir=tf/$STAGE init'
      - 'dotenv -e .env.$STAGE -- tfenv terraform  -chdir=tf/$STAGE plan -out=.tfplan-$STAGE'

  post_build:
    commands:
      - 'echo "Running terraform apply for common environment resources."'
      - 'dotenv -e .env.$STAGE -- tfenv terraform -chdir=tf/common apply .tfplan-common'
      - 'terraform -chdir=tf/common output -json > tf/common/.tfoutput.json'
      - 'echo "Running terraform apply for $STAGE environment resources."'
      - 'dotenv -e .env.$STAGE -- tfenv terraform -chdir=tf/$STAGE apply .tfplan-$STAGE'
      - 'terraform -chdir=tf/$STAGE output -json > tf/$STAGE/.tfoutput.json'
      - 'yarn run deploy:since-$(git branch --show-current)'
      - '[ $STAGE = "DUMMYSTAGE" ] \
          && dotenv -e .env.$STAGE -- yarn run new-version \ 
          || echo "Skipping versioning for stage: $STAGE"'
      - 'echo "TBD: Save some artifacts or something"'

cache:
  paths:
    - /usr/local/lib
    - /usr/bin