version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - 'apt-get -y update'
      - 'npm install -g yarn gatsby serverless'
      - 'yarn install --production'
  build:
    commands:
      - 'yarn run build'
  post_build:
    commands:
      - 'yarn run deploy'
cache:
  paths:
    - 'web/.cache/*'
    - 'web/public/*'
    - 'api/services/newsletter/.webpack/*'
    - 'api/services/photos/.webpack/*'
