# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Review PR Testing

on:
  pull_request:
    branches: [ review ]

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      STAGE: review
      GIT_BRANCH: review

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fetch git history for all tags and branches
      run: git fetch

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MEANDERING_ROCKS_REVIEW_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.MEANDERING_ROCKS_REVIEW_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: ${{ secrets.MEANDERING_ROCKS_REVIEW_AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 3000

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Copy .env.review file into repository
      run: 'aws s3 cp s3://meandering-rocks-configuration/env/.env.$STAGE .env.$STAGE'
    
    - name: Make utils scripts executable
      run: chmod a+rx utils -R

    - name: Install global/cli depedencies
      run: |
        npm install -g yarn json dotenv-cli
        mkdir -p $HOME/.local/bin
        wget -O $HOME/.local/bin/tfenv https://github.com/cloudposse/tfenv/releases/download/0.4.0/tfenv_linux_amd64
        chmod +x $HOME/.local/bin/tfenv
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install package dependencies
      run: yarn install

    - name: Initialize Terraform Environments
      run: './utils/tf-init.sh'

    - name: Test packages
      run: 'dotenv -e .env.$STAGE -- yarn run test:since-$GIT_BRANCH'

    - name: 'Terraform planning environment resources for stage: common'
      run: 'dotenv -e .env.$STAGE -- tfenv terraform -chdir=tf/common plan'

    - name: 'Terraform planning environment resources for stage: review'
      run: 'dotenv -e .env.$STAGE -- tfenv terraform  -chdir=tf/$STAGE plan'